#!/usr/bin/env ruby

require 'aws-sdk'

def s3_create_bucket(s3, bucket_name)
  s3.buckets.create(bucket_name)
end

def s3_put(s3, opts)
  (bucket_name, path, file_name) = opts
  bucket = s3.buckets[bucket_name]
  o = bucket.objects[path]
  o.write(:file => file_name, :acl => :public_read)
end

AWS.config({
  :access_key_id => ENV['AWS_ID'],
  :secret_access_key => ENV['AWS_SECRET']
})

s3 = AWS::S3.new

cmd = ARGV[0]
case cmd
when 'create'
  ARGV.shift
  s3_create_bucket(s3, ARGV[0])

when 'put'
  ARGV.shift
  s3_put(s3, ARGV)
  
else 
  raise("Unknown command '#{cmd}'")
end
